package gendesc

import (
	"errors"
	"go/ast"
	"go/build"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestDescribe(t *testing.T) {
	for _, tc := range []struct{ name, doc, want string }{
		{"StampDir", "StampDir ensures the /var/lib/x stamp directory.\n", "Ensures the /var/lib/x stamp directory"},
		{"Packages", "Packages installs ksh (script\ninterpreter) and yum-utils. More text.\n", "Installs ksh (script interpreter) and yum-utils"},
		{"RcConf", "RcConf sets vm_enable in rc.conf, e.g. YES. Then more.\n", "Sets vm_enable in rc.conf, e.g"},
		{"Keys", "rotates the keys of J. Doe. More.\n", "Rotates the keys of J. Doe"},
		{"Empty", "Empty.\n", "Empty"},
		{"X", "", ""},
	} {
		if got := Describe(tc.name, tc.doc); got != tc.want {
			t.Errorf("Describe(%q, %q) = %q, want %q", tc.name, tc.doc, got, tc.want)
		}
	}
}

func TestGenerate(t *testing.T) {
	dir := t.TempDir()
	src := `package recipe

type Unattended struct{}

// Script installs the wrapper script.
func (Unattended) Script() {}

// Cron installs the cron entry.
//
// Longer explanation.
func (*Unattended) Cron() {}

// Hand keeps its hand-written description.
func (Unattended) Hand() {}

func (Unattended) DescHand() string { return "Hand-written" }

func (Unattended) NoDoc() {}

// helper is unexported.
func (Unattended) helper() {}

// WithArgs is not a task.
func (Unattended) WithArgs(int) {}

// OptsCron is a companion.
func (Unattended) OptsCron() {}
`
	if err := os.WriteFile(filepath.Join(dir, "recipe.go"), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	stale := "package recipe\n\nfunc (Unattended) DescNoDoc() string { return \"stale\" }\n"
	if err := os.WriteFile(filepath.Join(dir, DefaultFile), []byte(stale), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := Generate(dir, DefaultFile)
	if err != nil {
		t.Fatal(err)
	}
	want := `// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package recipe

func (Unattended) DescCron() string { return "Installs the cron entry" }

func (Unattended) DescScript() string { return "Installs the wrapper script" }
`
	if string(got) != want {
		t.Fatalf("Generate =\n%s\nwant\n%s", got, want)
	}
	if strings.Contains(string(got), "stale") {
		t.Fatal("the previous output file was read as input")
	}
}

func TestGenerateNothing(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "a.go"), []byte("package a\n\ntype T struct{}\n\nfunc (T) Run() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := Generate(dir, DefaultFile)
	if err != nil || got != nil {
		t.Fatalf("Generate = %q, %v; want nil, nil", got, err)
	}
}

// A method defined per GOOS gets a single companion, else desc_gen.go
// declares DescX twice and the package no longer builds.
func TestGeneratePerOSMethodOnce(t *testing.T) {
	dir := t.TempDir()
	write := func(name, body string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("s.go", "package recipe\n\ntype S struct{}\n")
	write("s_linux.go", "package recipe\n\n// Setup installs the service.\nfunc (S) Setup() {}\n")
	write("s_freebsd.go", "package recipe\n\n// Setup installs the service.\nfunc (S) Setup() {}\n")
	out, err := Generate(dir, DefaultFile)
	if err != nil {
		t.Fatal(err)
	}
	if n := strings.Count(string(out), "DescSetup"); n != 1 {
		t.Fatalf("DescSetup declared %d times:\n%s", n, out)
	}
	write("s_freebsd.go", "package recipe\n\n// Setup installs the rc.d service.\nfunc (S) Setup() {}\n")
	if _, err := Generate(dir, DefaultFile); err == nil {
		t.Fatal("differing per-OS doc comments: want an error")
	}
}

// Every hard-coded port still exists in the running toolchain; a port the
// toolchain added is only logged, as the list then merely misses it.
func TestPlatformsKnown(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("no go command:", err)
	}
	b, err := exec.Command("go", "tool", "dist", "list").Output()
	if err != nil {
		t.Skip("go tool dist list:", err)
	}
	have := map[string]bool{}
	for _, l := range strings.Fields(string(b)) {
		have[l] = true
	}
	known := map[string]bool{}
	for _, p := range platforms {
		known[p.String()] = true
		if !have[p.String()] {
			t.Errorf("port %s is gone from go tool dist list; update platforms", p)
		}
	}
	for l := range have {
		if !known[l] {
			t.Logf("go tool dist list has port %s that platforms lacks", l)
		}
	}
}

// setOf returns the targets for which in is true.
func setOf(in func(target) bool) targetSet {
	s := make(targetSet, len(targets))
	for i, t := range targets {
		s[i] = in(t)
	}
	return s
}

func TestTargetSetString(t *testing.T) {
	for _, tc := range []struct {
		name string
		in   func(target) bool
		want string
	}{
		{"all", func(target) bool { return true }, "every platform"},
		{"cgo", func(t target) bool { return t.cgo }, "every platform with cgo"},
		{"no cgo", func(t target) bool { return !t.cgo }, "every platform without cgo"},
		{"few", func(t target) bool { return t.p.goos == "windows" }, "windows/386, windows/amd64, windows/arm64"},
		{"many", func(t target) bool { return t.p.goos == "linux" }, "linux/386, linux/amd64, linux/arm and 10 more"},
		{"one variant", func(t target) bool { return t.p.String() == "darwin/arm64" && t.cgo }, "darwin/arm64 with cgo"},
		{"mixed", func(t target) bool {
			return t.p.String() == "js/wasm" || t.p.String() == "darwin/arm64" && !t.cgo
		}, "darwin/arm64 without cgo, js/wasm"},
	} {
		if got := setOf(tc.in).String(); got != tc.want {
			t.Errorf("%s: String() = %q, want %q", tc.name, got, tc.want)
		}
	}
}

// writeFiles writes name -> content into a new temporary directory.
func writeFiles(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

const (
	fileT = "package recipe\n\ntype T struct{}\n\n// Bar installs bar.\nfunc (T) Bar() {}\n"
	declS = "type S struct{}\n\n// Foo installs foo.\nfunc (*S) Foo() {}\n"
	fileS = "package recipe\n\n" + declS
)

// Files go build never selects without custom -tags are not read: _x.go,
// .x.go (not even parsed) and files whose constraint no platform satisfies.
func TestGenerateSkipsUnbuiltFiles(t *testing.T) {
	gen := "package main\n\ntype G struct{}\n\n// Gen generates.\nfunc (G) Gen() {}\n"
	dir := writeFiles(t, map[string]string{
		"t.go":        fileT,
		"_x.go":       "not Go at all",
		".x.go":       "not Go at all",
		"gen.go":      "//go:build ignore\n\n" + gen,
		"tools.go":    "//go:build ignore && tools\n\n" + gen,
		"legacy.go":   "// +build ignore\n\n" + gen,
		"integ.go":    "//go:build integration\n\n" + gen,
		"notyet.go":   "//go:build go1.999\n\n" + gen,
		"nowhere.go":  "//go:build linux && windows\n\n" + gen,
		"v3.go":       "//go:build amd64.v3\n\n" + gen,
		"_s_linux.go": fileS,
	})
	got, err := Generate(dir, DefaultFile)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.\n\npackage recipe\n\n" +
		"func (T) DescBar() string { return \"Installs bar\" }\n"
	if string(got) != want {
		t.Fatalf("Generate =\n%s\nwant\n%s", got, want)
	}
}

// A receiver type missing on some platform where the generated file builds
// gets no companion there, which would not build: gonf-desc refuses and asks
// for a hand-written DescX.
func TestGenerateRefusesUncoveredReceiver(t *testing.T) {
	for name, tc := range map[string]struct{ file, body, missing string }{
		"GOOS suffix":      {"s_linux.go", fileS, "aix/ppc64, darwin/amd64, darwin/arm64 and "},
		"GOARCH suffix":    {"s_arm64.go", fileS, "aix/ppc64, android/386, android/amd64 and "},
		"GOOS_GOARCH":      {"s_darwin_arm64.go", fileS, "aix/ppc64, android/386, android/amd64 and "},
		"go:build line":    {"s.go", "//go:build linux\n\n" + fileS, "aix/ppc64, darwin/amd64, darwin/arm64 and "},
		"negated go:build": {"s.go", "//go:build !windows\n\n" + fileS, "is missing on windows/386, windows/amd64, windows/arm64;"},
		"+build line":      {"s.go", "// +build linux\n\n" + fileS, "aix/ppc64, darwin/amd64, darwin/arm64 and "},
		"cgo only":         {"s.go", "package recipe\n\nimport \"C\"\n\n" + declS, "is missing on every platform without cgo;"},
		"cgo tag":          {"s.go", "//go:build cgo\n\n" + fileS, "is missing on every platform without cgo;"},
	} {
		t.Run(name, func(t *testing.T) {
			dir := writeFiles(t, map[string]string{"t.go": fileT, tc.file: tc.body})
			out, err := Generate(dir, DefaultFile)
			if err == nil {
				t.Fatalf("Generate = nil error, want a refusal; output:\n%s", out)
			}
			msg := err.Error()
			for _, want := range []string{
				"S.Foo: desc_gen.go builds everywhere, but S (declared in " + tc.file + ")",
				tc.missing, "write DescFoo by hand next to S",
			} {
				if !strings.Contains(msg, want) {
					t.Errorf("error %q does not mention %q", msg, want)
				}
			}
			if strings.Contains(msg, "T.Bar") || strings.Contains(msg, "refused:") {
				t.Errorf("error %q blames more than S.Foo", msg)
			}
		})
	}
}

// Every refused method is reported, one per line under a heading.
func TestGenerateRefusesEveryUncoveredReceiver(t *testing.T) {
	dir := writeFiles(t, map[string]string{
		"s_linux.go":   "package recipe\n\ntype S struct{}\n\n// Foo installs foo.\nfunc (S) Foo() {}\n\n// Baz installs baz.\nfunc (S) Baz() {}\n",
		"u_freebsd.go": "package recipe\n\ntype U struct{}\n\n// Qux installs qux.\nfunc (U) Qux() {}\n",
	})
	_, err := Generate(dir, "descs.go")
	if err == nil {
		t.Fatal("Generate = nil error, want a refusal")
	}
	lines := strings.Split(err.Error(), "\n")
	if want := dir + ": 3 task methods refused:"; lines[0] != want {
		t.Errorf("heading %q, want %q", lines[0], want)
	}
	if len(lines) != 4 {
		t.Fatalf("error has %d lines, want a heading and 3:\n%s", len(lines), err)
	}
	for i, want := range []string{"\tS.Baz: descs.go builds everywhere", "\tS.Foo: ", "\tU.Qux: "} {
		if !strings.HasPrefix(lines[i+1], want) {
			t.Errorf("line %d = %q, want prefix %q", i+1, lines[i+1], want)
		}
	}
	if !strings.Contains(lines[3], "(declared in u_freebsd.go)") {
		t.Errorf("line 3 = %q, want the declaring file", lines[3])
	}
}

// A type declared in complementary files exists on every platform, so its
// companion is generated once and builds everywhere.
func TestGenerateComplementarySplit(t *testing.T) {
	for name, files := range map[string]map[string]string{
		"GOOS": {
			"s_linux.go": fileS,
			"s_other.go": "//go:build !linux\n\n" + fileS,
		},
		"cgo": {
			"s_cgo.go":   "//go:build cgo\n\npackage recipe\n\nimport \"C\"\n\n" + declS,
			"s_nocgo.go": "//go:build !cgo\n\n" + fileS,
		},
		"arch level": {
			"s_v1.go":    "//go:build amd64.v1\n\n" + fileS,
			"s_other.go": "//go:build !amd64\n\n" + fileS,
		},
	} {
		t.Run(name, func(t *testing.T) {
			dir := writeFiles(t, files)
			src, err := Generate(dir, DefaultFile)
			if err != nil {
				t.Fatal(err)
			}
			if n := strings.Count(string(src), "func (S) DescFoo()"); n != 1 {
				t.Fatalf("DescFoo generated %d times:\n%s", n, src)
			}
			if err := os.WriteFile(filepath.Join(dir, DefaultFile), src, 0o644); err != nil {
				t.Fatal(err)
			}
			for _, goos := range []string{"linux", "android", "darwin", "windows"} {
				typeCheck(t, dir, goos)
			}
		})
	}
}

// Only the platforms where the generated file builds count: a linux-only
// package is accepted with -o desc_linux.go, refused with the default name,
// and refused with a name for another platform.
func TestGenerateOutputNameConstraint(t *testing.T) {
	dir := writeFiles(t, map[string]string{"s_linux.go": fileS})
	if _, err := Generate(dir, DefaultFile); err == nil || !strings.Contains(err.Error(), "desc_gen.go builds everywhere") {
		t.Errorf("default -o: error %v, want a refusal", err)
	}
	_, err := Generate(dir, "desc_freebsd.go")
	want := "S.Foo: desc_freebsd.go builds on freebsd/386, freebsd/amd64, freebsd/arm, freebsd/arm64, where S (declared in s_linux.go) is missing"
	if err == nil || !strings.Contains(err.Error(), want) {
		t.Errorf("-o desc_freebsd.go: error %v, want it to contain %q", err, want)
	}

	src, err := Generate(dir, "desc_linux.go")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(src), "func (S) DescFoo()") {
		t.Fatalf("output lacks DescFoo:\n%s", src)
	}
	if err := os.WriteFile(filepath.Join(dir, "desc_linux.go"), src, 0o644); err != nil {
		t.Fatal(err)
	}
	for _, goos := range []string{"linux", "android", "darwin"} {
		typeCheck(t, dir, goos)
	}
}

// The default architecture levels count as set, cumulatively; a higher
// level counts as a custom tag.
func TestBuildTargetsToolTags(t *testing.T) {
	src := []byte("//go:build amd64.v1 || arm.6 || riscv64.rva20u64 || wasm.signext\n\npackage p\n")
	got, err := buildTargets("x.go", src)
	if err != nil {
		t.Fatal(err)
	}
	for i, tg := range targets {
		want := tg.p.goarch == "amd64" || tg.p.goarch == "arm" || tg.p.goarch == "riscv64" || tg.p.goarch == "wasm"
		if got[i] != want {
			t.Errorf("%s (cgo %v): builds = %v, want %v", tg.p, tg.cgo, got[i], want)
		}
	}
	got, err = buildTargets("x.go", []byte("//go:build amd64.v2 || arm64.v8.1\n\npackage p\n"))
	if err != nil {
		t.Fatal(err)
	}
	if !got.none() {
		t.Errorf("non-default levels build on %s, want nowhere", got)
	}
}

// A file building only with custom tags still contributes its hand-written
// DescX: generating one too would declare it twice under -tags integration.
// Its own task methods get no companion, and a file of another package
// (a //go:build ignore generator) contributes nothing.
func TestGenerateTagOnlyHandWritten(t *testing.T) {
	dir := writeFiles(t, map[string]string{
		"t.go": fileT,
		"d.go": "//go:build integration\n\npackage recipe\n\n" +
			"func (T) DescBar() string { return \"Hand-written\" }\n\n// Qux installs qux.\nfunc (T) Qux() {}\n",
	})
	src, err := Generate(dir, DefaultFile)
	if err != nil || src != nil {
		t.Fatalf("Generate = %q, %v; want nil, nil (DescBar is hand-written)", src, err)
	}
	typeCheck(t, dir, "linux", "integration")

	dir = writeFiles(t, map[string]string{
		"t.go":   fileT,
		"gen.go": "//go:build ignore\n\npackage main\n\ntype T struct{}\n\nfunc (T) DescBar() string { return \"other\" }\n",
	})
	src, err = Generate(dir, DefaultFile)
	if err != nil || !strings.Contains(string(src), "func (T) DescBar()") {
		t.Fatalf("Generate = %q, %v; want DescBar generated", src, err)
	}
}

// A receiver missing somewhere is fine when nothing is generated for it: its
// DescX is hand-written next to it, or its task has no doc comment. The
// generated file then type-checks on every platform, including those that
// leave the constrained files out.
func TestGenerateConstrainedReceiverHandWritten(t *testing.T) {
	dir := writeFiles(t, map[string]string{
		"t.go":         fileT,
		"t_freebsd.go": "package recipe\n\n// Baz installs baz.\nfunc (T) Baz() {}\n",
		"t_linux.go":   "package recipe\n\n// Baz installs baz.\nfunc (T) Baz() {}\n",
		"s_linux.go": "package recipe\n\ntype S struct{}\n\n// Foo installs foo.\nfunc (S) Foo() {}\n\n" +
			"func (S) DescFoo() string { return \"Installs foo\" }\n\nfunc (S) NoDoc() {}\n",
		"v.go": "//go:build darwin\n\npackage recipe\n\ntype V struct{}\n\nfunc (V) NoDoc() {}\n",
	})
	src, err := Generate(dir, DefaultFile)
	if err != nil {
		t.Fatal(err)
	}
	got := string(src)
	for _, want := range []string{"func (T) DescBar()", "func (T) DescBaz()"} {
		if !strings.Contains(got, want) {
			t.Errorf("output lacks %q:\n%s", want, got)
		}
	}
	for _, bad := range []string{"(S)", "(V)"} {
		if strings.Contains(got, bad) {
			t.Errorf("output has a companion for constrained %s:\n%s", bad, got)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, DefaultFile), src, 0o644); err != nil {
		t.Fatal(err)
	}
	for _, goos := range []string{"linux", "darwin", "freebsd", "openbsd", "windows"} {
		typeCheck(t, dir, goos)
	}
}

// typeCheck type-checks the import-free package in dir as it builds for
// goos/amd64 without cgo and with -tags tags, i.e. with the files go build
// would pick there. A package with no file there passes.
func typeCheck(t *testing.T, dir, goos string, tags ...string) {
	t.Helper()
	ctxt := build.Default
	ctxt.GOOS, ctxt.GOARCH, ctxt.CgoEnabled, ctxt.BuildTags = goos, "amd64", false, tags
	pkg, err := ctxt.ImportDir(dir, 0)
	var none *build.NoGoError
	if errors.As(err, &none) {
		return // nothing builds there, the generated file neither
	}
	if err != nil {
		t.Fatalf("GOOS=%s: %v", goos, err)
	}
	fset := token.NewFileSet()
	var files []*ast.File
	for _, n := range pkg.GoFiles {
		f, err := parser.ParseFile(fset, filepath.Join(dir, n), nil, 0)
		if err != nil {
			t.Fatal(err)
		}
		files = append(files, f)
	}
	if _, err := new(types.Config).Check(pkg.Name, fset, files, nil); err != nil {
		t.Errorf("GOOS=%s: %v (files %v)", goos, err, pkg.GoFiles)
	}
}
