package gendesc

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDescribe(t *testing.T) {
	for _, tc := range []struct{ name, doc, want string }{
		{"StampDir", "StampDir ensures the /var/lib/x stamp directory.\n", "Ensures the /var/lib/x stamp directory"},
		{"Packages", "Packages installs ksh (script\ninterpreter) and yum-utils. More text.\n", "Installs ksh (script interpreter) and yum-utils"},
		{"RcConf", "RcConf sets vm_enable in rc.conf, e.g. YES. Then more.\n", "Sets vm_enable in rc.conf, e.g"},
		{"Keys", "rotates the keys of J. Doe. More.\n", "Rotates the keys of J. Doe"},
		{"Empty", "Empty.\n", "Empty"},
		{"X", "", ""},
	} {
		if got := Describe(tc.name, tc.doc); got != tc.want {
			t.Errorf("Describe(%q, %q) = %q, want %q", tc.name, tc.doc, got, tc.want)
		}
	}
}

func TestGenerate(t *testing.T) {
	dir := t.TempDir()
	src := `package recipe

type Unattended struct{}

// Script installs the wrapper script.
func (Unattended) Script() {}

// Cron installs the cron entry.
//
// Longer explanation.
func (*Unattended) Cron() {}

// Hand keeps its hand-written description.
func (Unattended) Hand() {}

func (Unattended) DescHand() string { return "Hand-written" }

func (Unattended) NoDoc() {}

// helper is unexported.
func (Unattended) helper() {}

// WithArgs is not a task.
func (Unattended) WithArgs(int) {}

// OptsCron is a companion.
func (Unattended) OptsCron() {}
`
	if err := os.WriteFile(filepath.Join(dir, "recipe.go"), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	stale := "package recipe\n\nfunc (Unattended) DescNoDoc() string { return \"stale\" }\n"
	if err := os.WriteFile(filepath.Join(dir, DefaultFile), []byte(stale), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := Generate(dir, DefaultFile)
	if err != nil {
		t.Fatal(err)
	}
	want := `// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package recipe

func (Unattended) DescCron() string { return "Installs the cron entry" }

func (Unattended) DescScript() string { return "Installs the wrapper script" }
`
	if string(got) != want {
		t.Fatalf("Generate =\n%s\nwant\n%s", got, want)
	}
	if strings.Contains(string(got), "stale") {
		t.Fatal("the previous output file was read as input")
	}
}

func TestGenerateNothing(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "a.go"), []byte("package a\n\ntype T struct{}\n\nfunc (T) Run() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := Generate(dir, DefaultFile)
	if err != nil || got != nil {
		t.Fatalf("Generate = %q, %v; want nil, nil", got, err)
	}
}
