// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package web

func (Web) DescConfig() string { return "Writes the web server config" }

func (Web) DescContent() string { return "Publishes the start page" }

func (Web) DescDocroot() string { return "Creates the document root" }

func (Web) DescLogrotate() string { return "Rotates the web server logs (OpenBSD only)" }
