// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package frontend

func (Frontend) DescAccount() string { return "Creates the deploy account that owns the site's files" }

func (Frontend) DescConfig() string {
	return "Installs and validates the httpd configuration and keeps httpd running"
}

func (Frontend) DescContent() string { return "Publishes the site to the document root" }

func (Frontend) DescFirewall() string {
	return "Opens HTTP in firewalld, on front ends that have firewalld"
}

func (Frontend) DescLogrotate() string {
	return "Rotates the httpd logs nightly, each front end at its own time"
}

func (Frontend) DescPackages() string { return "Installs Apache httpd and its tools" }

func (Frontend) DescTuning() string { return "Raises the listen backlog for busy front ends" }
