package api

import (
	"fmt"
	"reflect"
	"runtime"
	"slices"
	"strings"
)

// This file answers, by reflection, the questions RegisterMethods needs
// about a method that a registered struct may promote from an embedded
// field (a StructOption marker's StructTaskOptions, or a companion or task
// method): which type declares it, through which chain of embedded fields
// it is promoted, and whether calling it would dereference a nil pointer
// or interface on that chain. Such a call panics, and a nil declaration is
// recipe misuse that must be reported as a declaration error instead.

// maxInterfaceHops bounds nilEmbed's walk through interface values, whose
// dynamic type may promote the method again; real chains have one or two.
const maxInterfaceHops = 16

// declaresMethod reports whether t itself declares the method name (any
// signature), as opposed to promoting it from an embedded field, and
// whether that declaration has a pointer receiver; an interface type counts
// when it has the method. A method set cannot tell a declared method from a
// promoted one, so this asks the runtime where the method's code is: a
// promoted method is a compiler-generated wrapper whose file is
// "<autogenerated>".
func declaresMethod(t reflect.Type, name string) (declared, pointerReceiver bool) {
	if t.Kind() == reflect.Interface {
		_, ok := t.MethodByName(name)
		return ok, false
	}
	// A value-receiver method is in both method sets, so T is checked
	// first; one found only on *T has a pointer receiver.
	for i, mt := range []reflect.Type{t, reflect.PointerTo(t)} {
		m, ok := mt.MethodByName(name)
		if !ok {
			continue
		}
		fn := runtime.FuncForPC(m.Func.Pointer())
		if fn == nil {
			return false, false
		}
		file, _ := fn.FileLine(fn.Entry())
		declared = file != "<autogenerated>"
		return declared, declared && i == 1
	}
	return false, false
}

// declaresStructTaskOptions reports whether t itself declares
// StructTaskOptions (declaresMethod).
func declaresStructTaskOptions(t reflect.Type) bool {
	declared, _ := declaresMethod(t, "StructTaskOptions")
	return declared
}

// promotionPath returns the embedded-field index path from t (not a
// pointer) to the type declaring the method name, following Go's selector
// rule: a breadth-first search over embedded types that stops at the
// shallowest depth with a declaration. It returns an empty path when t
// declares the method itself, and false when nothing declares it or the
// shallowest depth is ambiguous (the method is then not in the method set).
// Each type is expanded at most once (visited), so a recursive embed graph
// costs time linear in its embedded fields, as in reflect's FieldByName.
func promotionPath(t reflect.Type, name string) ([]int, bool) {
	type scan struct {
		typ   reflect.Type
		index []int
	}
	current := []scan{{typ: t}}
	visited := map[reflect.Type]bool{}
	for len(current) > 0 {
		count := map[reflect.Type]int{}
		for _, s := range current {
			count[s.typ]++
		}
		var next []scan
		var found []int
		matches := 0
		for _, s := range current {
			if visited[s.typ] {
				continue // seen at this or a shallower depth, which wins
			}
			visited[s.typ] = true
			if declared, _ := declaresMethod(s.typ, name); declared {
				matches += count[s.typ] // one type reached twice is ambiguous too
				found = s.index
				continue
			}
			if s.typ.Kind() != reflect.Struct {
				continue
			}
			for i := 0; i < s.typ.NumField(); i++ {
				f := s.typ.Field(i)
				if !f.Anonymous {
					continue
				}
				ft := f.Type
				if ft.Kind() == reflect.Pointer {
					ft = ft.Elem()
				}
				next = append(next, scan{typ: ft, index: append(slices.Clone(s.index), i)})
			}
		}
		switch {
		case matches == 1:
			return found, true
		case matches > 1:
			return nil, false
		}
		current = next
	}
	return nil, false
}

// nilEmbed follows the chain of embedded fields that method is promoted
// through, starting at v (named name, "" for the registered struct itself),
// and returns the dotted field path to the first nil pointer or interface
// on it — which calling the method would dereference — or "" when there is
// none: v is a nil marker field, an interface holding a nil pointer, or a
// struct such as Base in type Base struct{ *RequiresRoot } whose promoting
// field is nil. refuse is true for such a path.
//
// A nil pointer to a type that declares method on its pointer receiver is
// returned with refuse false: calling it dereferences nothing on the way
// (it is legal Go) and the method may handle a nil receiver itself, so the
// caller calls it through callNilReceiver. That can only be the last hop,
// since the declaration ends the chain.
//
// With ownedOnly, only the part of the chain held in v's own memory is
// checked: the walk stops (reporting nothing) where it would follow a
// non-nil pointer or interface other than v itself, since the fields
// behind it are shared and may still be set later (checkDeferred).
func nilEmbed(v reflect.Value, name, method string, ownedOnly bool) (path string, refuse bool) {
	path = name
	start := true // v itself may be dereferenced even with ownedOnly
	for range maxInterfaceHops {
		for v.Kind() == reflect.Pointer || v.Kind() == reflect.Interface {
			if v.IsNil() {
				if v.Kind() == reflect.Pointer {
					if declared, ptrRecv := declaresMethod(v.Type().Elem(), method); declared && ptrRecv {
						return path, false
					}
				}
				return path, true
			}
			if ownedOnly && !start {
				return "", false
			}
			v = v.Elem()
		}
		start = false
		index, ok := promotionPath(v.Type(), method)
		if !ok || len(index) == 0 {
			return "", false // not promoted: nothing to dereference
		}
		for n, i := range index {
			path = joinFieldPath(path, v.Type().Field(i).Name)
			v = v.Field(i)
			if n < len(index)-1 && v.Kind() == reflect.Pointer {
				if v.IsNil() {
					return path, true // an intermediate embed is nil
				}
				if ownedOnly {
					return "", false
				}
				v = v.Elem()
			}
		}
		// v is now the declaring field: the loop checks it for nil and, if
		// it is an interface, follows its dynamic value.
	}
	return "", false
}

// joinFieldPath appends field to the dotted path.
func joinFieldPath(path, field string) string {
	if path == "" {
		return field
	}
	return path + "." + field
}

// callNilReceiver runs call. nilRecv is the path of the nil pointer the
// called method runs on (nilEmbed with refuse false), or "" for a non-nil
// receiver, where call runs as is. A nil receiver is legal Go, but a
// method that does not handle one dereferences it. Fail-safe, any nil
// pointer dereference of the call is reported through onNil instead of
// crashing the recipe (most likely, though not certainly, the nil
// receiver's); every other panic propagates unchanged.
func callNilReceiver[T any](nilRecv string, onNil func(r any) error, call func() (T, error)) (res T, err error) {
	if nilRecv == "" {
		return call()
	}
	defer func() {
		if r := recover(); r != nil {
			if !isNilDereference(r) {
				panic(r)
			}
			var zero T
			res, err = zero, onNil(r)
		}
	}()
	return call()
}

// isNilDereference reports whether the recovered value r is the runtime's
// nil pointer dereference error (it has no exported type of its own).
func isNilDereference(r any) bool {
	re, ok := r.(runtime.Error)
	return ok && strings.Contains(re.Error(), "nil pointer dereference")
}

// callPromoted calls fn, which calls the method name of the registered
// struct rv (a companion such as Opts or WhenX, or a task method), after
// checking the chain the method is promoted through: a nil embedded field
// on it is returned as an error instead of letting the call panic, and a
// nil pointer-receiver declaration is called through callNilReceiver.
func callPromoted[T any](rv reflect.Value, name string, fn func() (T, error)) (T, error) {
	nilRecv, err := checkPromoted(rv, name, false)
	if err != nil {
		var zero T
		return zero, err
	}
	return callNilReceiver(nilRecv, func(r any) error {
		return fmt.Errorf("%s is called on the nil embedded field %s and panicked with a nil pointer dereference (probably its nil receiver): %v", name, nilRecv, r)
	}, fn)
}

// checkPromoted returns an error when calling the method name of rv would
// dereference a nil embedded field (only one held in rv's own memory with
// ownedOnly, see nilEmbed), else the nil-receiver path for callNilReceiver
// ("" for a non-nil receiver).
func checkPromoted(rv reflect.Value, name string, ownedOnly bool) (string, error) {
	path, refuse := nilEmbed(rv, "", name, ownedOnly)
	if refuse {
		return "", fmt.Errorf("%s is promoted through the nil embedded field %s", name, path)
	}
	return path, nil
}
